/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Beneficiary model module.
* @module model/Beneficiary
* @version 0.0.1
*/
export default class Beneficiary {
    /**
    * Constructs a new <code>Beneficiary</code>.
    * @alias module:model/Beneficiary
    * @class
    * @param institutionName {String} 
    */

    constructor(institutionName) {
        
        
        this['institutionName'] = institutionName;
        
    }

    /**
    * Constructs a <code>Beneficiary</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Beneficiary} obj Optional instance to populate.
    * @return {module:model/Beneficiary} The populated <code>Beneficiary</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Beneficiary();
                        
            
            if (data.hasOwnProperty('institutionName')) {
                obj['institutionName'] = ApiClient.convertToType(data['institutionName'], 'String');
            }
            if (data.hasOwnProperty('userLegalName')) {
                obj['userLegalName'] = ApiClient.convertToType(data['userLegalName'], 'String');
            }
            if (data.hasOwnProperty('userPhysicalAddress')) {
                obj['userPhysicalAddress'] = ApiClient.convertToType(data['userPhysicalAddress'], 'String');
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} institutionName
    */
    institutionName = undefined;
    /**
    * @member {String} userLegalName
    */
    userLegalName = undefined;
    /**
    * @member {String} userPhysicalAddress
    */
    userPhysicalAddress = undefined;
    /**
    * @member {String} accountId
    */
    accountId = undefined;




}
