/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TravelRule from './TravelRule';

/**
* The Compliance model module.
* @module model/Compliance
* @version 0.0.1
*/
export default class Compliance {
    /**
    * Constructs a new <code>Compliance</code>.
    * @alias module:model/Compliance
    * @class
    * @param type {String} 
    * @param data {module:model/TravelRule} 
    */

    constructor(type, data) {
        
        OneOfSignatureWrapperMessage.call(this);
        this['type'] = type;
        this['data'] = data;
        
    }

    /**
    * Constructs a <code>Compliance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Compliance} obj Optional instance to populate.
    * @return {module:model/Compliance} The populated <code>Compliance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Compliance();
                        
            
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = TravelRule.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {module:model/TravelRule} data
    */
    data = undefined;

    // Implement OneOfSignatureWrapperMessage interface:
    


}
