/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvoiceComplianceHashes from './InvoiceComplianceHashes';
import PaymentInformation from './PaymentInformation';

/**
* The Invoice model module.
* @module model/Invoice
* @version 0.0.1
*/
export default class Invoice {
    /**
    * Constructs a new <code>Invoice</code>.
    * @alias module:model/Invoice
    * @class
    * @param nonce {String} 
    * @param expirationTime {String} 
    * @param paymentInformation {module:model/PaymentInformation} 
    * @param complianceRequirements {Array.<String>} 
    */

    constructor(nonce, expirationTime, paymentInformation, complianceRequirements) {
        
        
        this['nonce'] = nonce;
        this['expirationTime'] = expirationTime;
        this['paymentInformation'] = paymentInformation;
        this['complianceRequirements'] = complianceRequirements;
        
    }

    /**
    * Constructs a <code>Invoice</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Invoice} obj Optional instance to populate.
    * @return {module:model/Invoice} The populated <code>Invoice</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Invoice();
                        
            
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
            }
            if (data.hasOwnProperty('expirationTime')) {
                obj['expirationTime'] = ApiClient.convertToType(data['expirationTime'], 'String');
            }
            if (data.hasOwnProperty('paymentInformation')) {
                obj['paymentInformation'] = PaymentInformation.constructFromObject(data['paymentInformation']);
            }
            if (data.hasOwnProperty('complianceRequirements')) {
                obj['complianceRequirements'] = ApiClient.convertToType(data['complianceRequirements'], ['String']);
            }
            if (data.hasOwnProperty('memo')) {
                obj['memo'] = ApiClient.convertToType(data['memo'], 'String');
            }
            if (data.hasOwnProperty('complianceHashes')) {
                obj['complianceHashes'] = ApiClient.convertToType(data['complianceHashes'], [InvoiceComplianceHashes]);
            }
        }
        return obj;
    }

    /**
    * @member {String} nonce
    */
    nonce = undefined;
    /**
    * @member {String} expirationTime
    */
    expirationTime = undefined;
    /**
    * @member {module:model/PaymentInformation} paymentInformation
    */
    paymentInformation = undefined;
    /**
    * @member {Array.<String>} complianceRequirements
    */
    complianceRequirements = undefined;
    /**
    * @member {String} memo
    */
    memo = undefined;
    /**
    * @member {Array.<module:model/InvoiceComplianceHashes>} complianceHashes
    */
    complianceHashes = undefined;




}
