/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InvoiceComplianceHashes model module.
* @module model/InvoiceComplianceHashes
* @version 0.0.1
*/
export default class InvoiceComplianceHashes {
    /**
    * Constructs a new <code>InvoiceComplianceHashes</code>.
    * @alias module:model/InvoiceComplianceHashes
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InvoiceComplianceHashes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InvoiceComplianceHashes} obj Optional instance to populate.
    * @return {module:model/InvoiceComplianceHashes} The populated <code>InvoiceComplianceHashes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceComplianceHashes();
                        
            
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {String} hash
    */
    hash = undefined;




}
