/**
 * test
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Mapping model module.
* @module model/Mapping
* @version 1.0
*/
export default class Mapping {
    /**
    * Constructs a new <code>Mapping</code>.
    * @alias module:model/Mapping
    * @class
    * @param address {String} 
    */

    constructor(address) {
        
        
        this['address'] = address;
        
    }

    /**
    * Constructs a <code>Mapping</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Mapping} obj Optional instance to populate.
    * @return {module:model/Mapping} The populated <code>Mapping</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mapping();
                        
            
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} address
    */
    address = undefined;




}
