/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OneOfSignatureWrapperMessage model module.
* @module model/OneOfSignatureWrapperMessage
* @version 0.0.1
*/
export default class OneOfSignatureWrapperMessage {
    /**
    * Constructs a new <code>OneOfSignatureWrapperMessage</code>.
    * @alias module:model/OneOfSignatureWrapperMessage
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfSignatureWrapperMessage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfSignatureWrapperMessage} obj Optional instance to populate.
    * @return {module:model/OneOfSignatureWrapperMessage} The populated <code>OneOfSignatureWrapperMessage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfSignatureWrapperMessage();
                        
            
        }
        return obj;
    }





}
