/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CryptoAddressDetails from './CryptoAddressDetails';

/**
* The PaymentInformation model module.
* @module model/PaymentInformation
* @version 0.0.1
*/
export default class PaymentInformation {
    /**
    * Constructs a new <code>PaymentInformation</code>.
    * @alias module:model/PaymentInformation
    * @class
    * @param addressDetailsType {String} 
    * @param addressDetails {module:model/CryptoAddressDetails} 
    */

    constructor(addressDetailsType, addressDetails) {
        
        
        this['addressDetailsType'] = addressDetailsType;
        this['addressDetails'] = addressDetails;
        
    }

    /**
    * Constructs a <code>PaymentInformation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentInformation} obj Optional instance to populate.
    * @return {module:model/PaymentInformation} The populated <code>PaymentInformation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentInformation();
                        
            
            if (data.hasOwnProperty('addressDetailsType')) {
                obj['addressDetailsType'] = ApiClient.convertToType(data['addressDetailsType'], 'String');
            }
            if (data.hasOwnProperty('addressDetails')) {
                obj['addressDetails'] = CryptoAddressDetails.constructFromObject(data['addressDetails']);
            }
            if (data.hasOwnProperty('proof_of_control_signature')) {
                obj['proof_of_control_signature'] = ApiClient.convertToType(data['proof_of_control_signature'], 'String');
            }
            if (data.hasOwnProperty('paymentPointer')) {
                obj['paymentPointer'] = ApiClient.convertToType(data['paymentPointer'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} addressDetailsType
    */
    addressDetailsType = undefined;
    /**
    * @member {module:model/CryptoAddressDetails} addressDetails
    */
    addressDetails = undefined;
    /**
    * @member {String} proof_of_control_signature
    */
    proof_of_control_signature = undefined;
    /**
    * @member {String} paymentPointer
    */
    paymentPointer = undefined;




}
