/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Receipt model module.
* @module model/Receipt
* @version 0.0.1
*/
export default class Receipt {
    /**
    * Constructs a new <code>Receipt</code>.
    * @alias module:model/Receipt
    * @class
    * @param invoiceHash {String} 
    * @param transactionConfirmation {String} 
    */

    constructor(invoiceHash, transactionConfirmation) {
        
        
        this['invoiceHash'] = invoiceHash;
        this['transactionConfirmation'] = transactionConfirmation;
        
    }

    /**
    * Constructs a <code>Receipt</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Receipt} obj Optional instance to populate.
    * @return {module:model/Receipt} The populated <code>Receipt</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Receipt();
                        
            
            if (data.hasOwnProperty('invoiceHash')) {
                obj['invoiceHash'] = ApiClient.convertToType(data['invoiceHash'], 'String');
            }
            if (data.hasOwnProperty('transactionConfirmation')) {
                obj['transactionConfirmation'] = ApiClient.convertToType(data['transactionConfirmation'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} invoiceHash
    */
    invoiceHash = undefined;
    /**
    * @member {String} transactionConfirmation
    */
    transactionConfirmation = undefined;




}
