/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Compliance from './Compliance';

/**
* The SignatureWrapperCompliance model module.
* @module model/SignatureWrapperCompliance
* @version 0.0.1
*/
export default class SignatureWrapperCompliance {
    /**
    * Constructs a new <code>SignatureWrapperCompliance</code>.
    * @alias module:model/SignatureWrapperCompliance
    * @class
    * @param messageType {String} 
    * @param message {module:model/Compliance} 
    * @param pkiType {String} 
    * @param pkiData {Array.<String>} 
    * @param publicKey {String} 
    * @param signature {String} 
    */

    constructor(messageType, message, pkiType, pkiData, publicKey, signature) {
        
        
        this['messageType'] = messageType;
        this['message'] = message;
        this['pkiType'] = pkiType;
        this['pkiData'] = pkiData;
        this['publicKey'] = publicKey;
        this['signature'] = signature;
        
    }

    /**
    * Constructs a <code>SignatureWrapperCompliance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SignatureWrapperCompliance} obj Optional instance to populate.
    * @return {module:model/SignatureWrapperCompliance} The populated <code>SignatureWrapperCompliance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignatureWrapperCompliance();
                        
            
            if (data.hasOwnProperty('messageType')) {
                obj['messageType'] = ApiClient.convertToType(data['messageType'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = Compliance.constructFromObject(data['message']);
            }
            if (data.hasOwnProperty('pkiType')) {
                obj['pkiType'] = ApiClient.convertToType(data['pkiType'], 'String');
            }
            if (data.hasOwnProperty('pkiData')) {
                obj['pkiData'] = ApiClient.convertToType(data['pkiData'], ['String']);
            }
            if (data.hasOwnProperty('publicKey')) {
                obj['publicKey'] = ApiClient.convertToType(data['publicKey'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} messageType
    */
    messageType = undefined;
    /**
    * @member {module:model/Compliance} message
    */
    message = undefined;
    /**
    * @member {String} pkiType
    */
    pkiType = undefined;
    /**
    * @member {Array.<String>} pkiData
    */
    pkiData = undefined;
    /**
    * @member {String} publicKey
    */
    publicKey = undefined;
    /**
    * @member {String} signature
    */
    signature = undefined;




}
