/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Beneficiary from './Beneficiary';
import Originator from './Originator';

/**
* The TravelRule model module.
* @module model/TravelRule
* @version 0.0.1
*/
export default class TravelRule {
    /**
    * Constructs a new <code>TravelRule</code>.
    * @alias module:model/TravelRule
    * @class
    * @param originator {module:model/Originator} 
    * @param beneficiary {module:model/Beneficiary} 
    */

    constructor(originator, beneficiary) {
        
        
        this['originator'] = originator;
        this['beneficiary'] = beneficiary;
        
    }

    /**
    * Constructs a <code>TravelRule</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TravelRule} obj Optional instance to populate.
    * @return {module:model/TravelRule} The populated <code>TravelRule</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TravelRule();
                        
            
            if (data.hasOwnProperty('originator')) {
                obj['originator'] = Originator.constructFromObject(data['originator']);
            }
            if (data.hasOwnProperty('beneficiary')) {
                obj['beneficiary'] = Beneficiary.constructFromObject(data['beneficiary']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Originator} originator
    */
    originator = undefined;
    /**
    * @member {module:model/Beneficiary} beneficiary
    */
    beneficiary = undefined;




}
