/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
* The Value model module.
* @module model/Value
* @version 0.0.1
*/
export default class Value {
    /**
    * Constructs a new <code>Value</code>.
    * @alias module:model/Value
    * @class
    * @param amount {String} 
    * @param scale {module:model/ModelObject} 
    */

    constructor(amount, scale) {
        
        
        this['amount'] = amount;
        this['scale'] = scale;
        
    }

    /**
    * Constructs a <code>Value</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Value} obj Optional instance to populate.
    * @return {module:model/Value} The populated <code>Value</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Value();
                        
            
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('scale')) {
                obj['scale'] = ApiClient.convertToType(data['scale'], ModelObject);
            }
        }
        return obj;
    }

    /**
    * @member {String} amount
    */
    amount = undefined;
    /**
    * @member {module:model/ModelObject} scale
    */
    scale = undefined;




}
