coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto 
        if_ci_failed: error
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto 
        if_ci_failed: error
