swagger: "2.0"
info:
  title: PayID
  version: '0.1'
servers:
  - url: 'https://'
# TODO(keefertaylor): Headers can be added in this file or manually set on the client. Evaluate and implement headers.
paths:
  '/{path}':
    parameters:
      - schema:
          type: string
        name: path
        in: path
        required: true
    get:
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  network:
                    type: string
        '404':
          description: Not Found
      operationId: get-path
components:
  schemas: {}
  securitySchemes: {}
