/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PayId);
  }
}(this, function(expect, PayId) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PayId.Originator();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Originator', function() {
    it('should create an instance of Originator', function() {
      // uncomment below and update the code to test Originator
      //var instane = new PayId.Originator();
      //expect(instance).to.be.a(PayId.Originator);
    });

    it('should have the property userLegalName (base name: "userLegalName")', function() {
      // uncomment below and update the code to test the property userLegalName
      //var instane = new PayId.Originator();
      //expect(instance).to.be();
    });

    it('should have the property accountId (base name: "accountId")', function() {
      // uncomment below and update the code to test the property accountId
      //var instane = new PayId.Originator();
      //expect(instance).to.be();
    });

    it('should have the property userPhysicalAddress (base name: "userPhysicalAddress")', function() {
      // uncomment below and update the code to test the property userPhysicalAddress
      //var instane = new PayId.Originator();
      //expect(instance).to.be();
    });

    it('should have the property institutionName (base name: "institutionName")', function() {
      // uncomment below and update the code to test the property institutionName
      //var instane = new PayId.Originator();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new PayId.Originator();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new PayId.Originator();
      //expect(instance).to.be();
    });

  });

}));
