/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PayId);
  }
}(this, function(expect, PayId) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PayId.SignatureWrapperInvoice();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SignatureWrapperInvoice', function() {
    it('should create an instance of SignatureWrapperInvoice', function() {
      // uncomment below and update the code to test SignatureWrapperInvoice
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be.a(PayId.SignatureWrapperInvoice);
    });

    it('should have the property messageType (base name: "messageType")', function() {
      // uncomment below and update the code to test the property messageType
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be();
    });

    it('should have the property pkiType (base name: "pkiType")', function() {
      // uncomment below and update the code to test the property pkiType
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be();
    });

    it('should have the property pkiData (base name: "pkiData")', function() {
      // uncomment below and update the code to test the property pkiData
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be();
    });

    it('should have the property publicKey (base name: "publicKey")', function() {
      // uncomment below and update the code to test the property publicKey
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be();
    });

    it('should have the property signature (base name: "signature")', function() {
      // uncomment below and update the code to test the property signature
      //var instane = new PayId.SignatureWrapperInvoice();
      //expect(instance).to.be();
    });

  });

}));
