/**
 * PayID
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Beneficiary from './model/Beneficiary';
import Compliance from './model/Compliance';
import CryptoAddressDetails from './model/CryptoAddressDetails';
import Invoice from './model/Invoice';
import InvoiceComplianceHashes from './model/InvoiceComplianceHashes';
import Originator from './model/Originator';
import PaymentInformation from './model/PaymentInformation';
import SignatureWrapperCompliance from './model/SignatureWrapperCompliance';
import SignatureWrapperInvoice from './model/SignatureWrapperInvoice';
import TravelRule from './model/TravelRule';
import Value from './model/Value';
import DefaultApi from './api/DefaultApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PayId = require('index'); // See note below*.
* var xxxSvc = new PayId.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PayId.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PayId.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PayId.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Beneficiary model constructor.
     * @property {module:model/Beneficiary}
     */
    Beneficiary,

    /**
     * The Compliance model constructor.
     * @property {module:model/Compliance}
     */
    Compliance,

    /**
     * The CryptoAddressDetails model constructor.
     * @property {module:model/CryptoAddressDetails}
     */
    CryptoAddressDetails,

    /**
     * The Invoice model constructor.
     * @property {module:model/Invoice}
     */
    Invoice,

    /**
     * The InvoiceComplianceHashes model constructor.
     * @property {module:model/InvoiceComplianceHashes}
     */
    InvoiceComplianceHashes,

    /**
     * The Originator model constructor.
     * @property {module:model/Originator}
     */
    Originator,

    /**
     * The PaymentInformation model constructor.
     * @property {module:model/PaymentInformation}
     */
    PaymentInformation,

    /**
     * The SignatureWrapperCompliance model constructor.
     * @property {module:model/SignatureWrapperCompliance}
     */
    SignatureWrapperCompliance,

    /**
     * The SignatureWrapperInvoice model constructor.
     * @property {module:model/SignatureWrapperInvoice}
     */
    SignatureWrapperInvoice,

    /**
     * The TravelRule model constructor.
     * @property {module:model/TravelRule}
     */
    TravelRule,

    /**
     * The Value model constructor.
     * @property {module:model/Value}
     */
    Value,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
